HeadArray:
- head-branch: ['wrong', 'new']

HeadString:
- head-branch: 'new'

HeadRegex:
- head-branch: ['^n']

BaseArray:
- base-branch: ['wrong', 'main']

BaseString:
- base-branch: 'main'

BaseRegex:
- base-branch: ['^m']