HeadArray:
- head-branch: ['wrong', 'new'] # "branch" patterns matched against new +

HeadArrayLast:
- all:
  - head-branch: ['wrong', 'new'] # "branch" patterns matched against new +
  # since only one pattern has to match we need to reflect it in the documentation properly

HeadString:
- head-branch: 'new' # "branch" patterns matched against new +

HeadRegex:
- head-branch: ['^n'] # "branch" pattern matched +

BaseArray:
- base-branch: ['wrong', 'main'] # "branch" patterns matched +

BaseString:
- base-branch: 'main' # "branch" patterns matched +

BaseRegex:
- base-branch: ['^m'] # "branch" patterns matched +

BaseArrayLast:
- all:
  - base-branch: ['wrong', 'main'] # "branch" patterns matched against main +
  # since only one pattern has to match we need to reflect it in the documentation properly