HeadArray:
- head-branch: ['new'] # добавить несколько элементов

HeadString:
- head-branch: 'new'

HeadRegex:
- head-branch: ['/e/'] # разобраться почему не работает

BaseArray:
- base-branch: ['main'] # добавить несколько элементов

BaseString:
- base-branch: 'main'

BaseRegex:
- base-branch: ['/ai/'] # разобраться почему не работает