CFString:
- changed-files: '**'

CFAny:
- any:
  - changed-files: ['**']

CFAll:
- all: 
  - changed-files: ['**']

CFAllAndAny:
- any:
  - changed-files: ['**', '**']
- all: 
  - changed-files: ['**', '**']