CFString:
- changed-files: '**' # works as ANY 

CFAny:
- any:
  - changed-files: ['**'] # "any" patterns matched +

CFAll:
- all: 
  - changed-files: ['**'] # "all" patterns matched all files +

CFAllAndAny:
- any:
  - changed-files: ['.*', '**'] # "any" patterns matched because one matched
- all: 
  - changed-files: ['**', '**'] # "all" patterns matched all files +