BranchesAndFilesAny:
- head-branch: ['new'] # "branch" patterns matched against new
- base-branch: ['main']
- changed-files: ['**']

BranchesAndFilesAll: # "all" patterns matched all configs
- all:
  - head-branch: ['new']
  - base-branch: ['main']
  - changed-files: ['**']

BranchesAndFilesAnyAndAll:
- any: # "any" patterns matched / the only one pattern was checked
  - changed-files: ['**', '**']
- all: # "all" patterns matched all configs
  - head-branch: ['new']
  - base-branch: ['main']
  - changed-files: ['**', '**']

BranchesAndFilesAnyLast:
- head-branch: ['adfaf']
- base-branch: ['afdasfa']
- changed-files: ['**'] # "any" patterns matched

BranchesAndFilesAnyDidn'tMatch: # "any" patterns did not match any configs
- head-branch: ['adfaf']
- base-branch: ['afdasfa']
- changed-files: ['.*']

BranchesAndFilesAllFirstMatch:
- all:
  - head-branch: ['new']
  - base-branch: ['adsfdfa'] #  "branch" patterns did not match against main
  - changed-files: ['.*']

BranchesAndFilesAnyAndAllDidn'tMatch:
- any:
  - changed-files: ['**', '**']
- all:
  - head-branch: ['new']
  - base-branch: ['main']
  - changed-files: ['.*'] #  "all" patterns did not match

BranchesAndFilesAnyDidn'tMatchAndAll: # "any" patterns did not match any files
- any:
  - changed-files: ['.*']
- all:
  - head-branch: ['new']
  - base-branch: ['main']
  - changed-files: ['**', '**']