HeadAndBaseAny: 
- head-branch: ['new'] # "branch" pattern matched
- base-branch: ['main']

HeadAndBaseAll:
- all: # "all" patterns matched all configs
  - head-branch: ['new']
  - base-branch: ['main']