name: Test the original action
on:
  - pull_request_target

jobs:
  # job1:
  #   name: Strings Array on top level
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #     issues: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@main
  #       with:
  #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
  #         configuration-path: .github/strings-array.yml

  # job2:
  #   name: Simple string on top level
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #     issues: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@main
  #       with:
  #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
  #         configuration-path: .github/simple-string.yml

  # job3:
  #   name: Non-existent config on top level
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #     issues: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@main
  #       with:
  #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
  #         configuration-path: .github/non-existent-config.yml

  # job4:
  #   name: Any on top lavel
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #     issues: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@main
  #       with:
  #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
  #         configuration-path: .github/any-on-top.yml

  # job5:
  #   name: Any and string on top lavel
  #   permissions:
  #     contents: read
  #     pull-requests: write
  #     issues: write
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/labeler@main
  #       with:
  #         repo-token: '${{ secrets.GITHUB_TOKEN }}'
  #         configuration-path: .github/any-and-string-on-top.yml

  job6:
    name: All and Any on top lavel
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/all-and-any.yml
