name: Test PR
on:
  - pull_request_target

jobs:
  job1:
    name: Strings Array
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/strings-array.yml

  job2:
    name: Simple string
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/simple-string.yml

  job3:
    name: Non-existent config
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/non-existent-config.yml

  job4:
    name: Any on top lavel
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/any-on-top.yml

  job5:
    name: Changed files
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/changed-files.yml

  job6:
    name: Changed files non-existent config
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/cf-non-existent-config.yml

  job7:
    name: Changed files string all
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/cf-string-all.yml

  job8:
    name: Changed files string any
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/cf-string-any.yml

  job9:
    name: Branches
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/branches.yml

  job10:
    name: Combine branch and files
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/combine-branch-and-files.yml

  job11:
    name: Combine branches and files
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/combine-branches-and-files.yml

  job12:
    name: Combine branches
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/combine-branches.yml

  job13:
    name: String array
    permissions:
      contents: read
      pull-requests: write
      issues: write
    runs-on: ubuntu-latest
    steps:
      - uses: joshdales/labeler@main
        with:
          repo-token: '${{ secrets.GITHUB_TOKEN }}'
          configuration-path: .github/cf-string-array.yml