name: Test Node
on:
  workflow_dispatch:

jobs:
  setup-node:
    name: Setup
    runs-on: macos-11
    steps: 
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          check-latest: true
