name: Python test

on:
  workflow_dispatch:
  
jobs:
  python-pip-dependencies-caching:
    name: Test python
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: pypy-3.9
          check-latest: true
