name: Test python
on:
  workflow_dispatch:

jobs:
  setup-python:
    name: Setup
    runs-on: macos-11
    steps:      
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: maksimzhukov/setup-python@main
      with:
        python-version-file: '.python-version'
        
    - name: Setup Python
      uses: maksimzhukov/setup-python@master
      with:
        python-version-file: '.python-version'
