name: Ubuntu
on:
  workflow_dispatch:
  
jobs:
  ubuntu22:
    name: Latest
    runs-on: ubuntu-latest
    steps:
    - run: |
        sudo npm install forever -g
        forever start server.js
        curl localhost:8008
        forever stop server.js
        
    
  ubuntu20:
    name: '20.04'
    runs-on: ubuntu-20.04
    steps:
    - run: |
        sudo npm install forever -g
        forever start server.js
        curl localhost:8008
        forever stop server.js
        
