name: Ubuntu
on:
  workflow_dispatch:
  
jobs:
  ubuntu22:
    name: Latest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install
      run: sudo npm install forever -g  
    - name: start
      run: |
        forever start server.js
        sudo curl localhost:8008
        forever stop server.js
        
    
  ubuntu20:
    name: '20.04'
    runs-on: ubuntu-20.04
    steps:    
    - uses: actions/checkout@v3
    - name: install
      run: sudo npm install forever -g  
    - name: start
      run: |
        forever start server.js
        sudo curl localhost:8008
        forever stop server.js
        
