name: Ubuntu

on:
  - workflow_dispatch:
  
jobs:
  ubuntu22:
    name: Latest
    runs-on: ubuntu-latest
    steps:
    - run: sudo netstat -tunlp
    
  ubuntu20:
    name: 20.04
    runs-on: ubuntu-20.04
    steps:
    - run: sudo netstat -tunlp
