name: Ubuntu test

on:
  - workflow_dispatch

jobs:
  test:
    name: Ubuntu test
    runs-on: ubuntu-latest
    steps:    
      - name: ulimit 1
        run: |
          sudo prlimit --pid $$ --nofile=1048576:1048576 
          ulimit -a
          
      - name: ulimit 2
        run: |
          sudo prlimit --pid $$ --rttime=unlimited
          ulimit -a
          
      - name: ulimit 3
        run: |
          ulimit -a

      - name: ulimit 3
        run: |
          prlimit
